version: "3.0"
services:
  jupyter_whale:
    build: 
      context: ./jupyter_whale/
      args:
        - JUPYTER_WHALE_SRC
    container_name: jupyter_base_whale
    image: ds/jupyter_base_whale
    entrypoint: ["sh", "-c"]
    command: ["pip freeze > jupyter_whale_requirements.txt.log && jupyter notebook --no-browser --port 8888 --ip=0.0.0.0"]
    expose:
      - "8888"
      - "80"
    ports:
      - "8888:8888"
      - "80:80"
    volumes:
      - ${JUPYTER_WHALE_SRC}:/home/ds/notebooks
